variable "deployer_ip_address" {
  type        = string
  description = "The Ip address of the compute resource deploying the module. This is used to allow access Key vault for the jump box secrets."
}

variable "location" {
  type        = string
  description = <<DESCRIPTION
Azure region where all resources should be deployed.

This specifies the primary Azure region for deploying the AI/ML landing zone infrastructure. All resources will be created in this region unless specifically configured otherwise in individual resource definitions.
DESCRIPTION
  nullable    = false
}

# This is required for most resource modules
variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where all resources will be deployed.

This resource group will contain all the AI/ML landing zone infrastructure components. The resource group should already exist or will be created as part of the deployment process.
DESCRIPTION
}

variable "vnet_definition" {
  type = object({
    name          = optional(string)
    address_space = string
  })
  description = <<DESCRIPTION
Configuration object for the Virtual Network (VNet) to be deployed.

- `name` - (Optional) The name of the Virtual Network. If not provided, a name will be generated.
- `address_space` - (Required) The address space for the Virtual Network in CIDR notation.
DESCRIPTION
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "jump_vm_definition" {
  type = object({
    name             = optional(string)
    sku              = optional(string, "Standard_B2s")
    tags             = optional(map(string), {})
    enable_telemetry = optional(bool, true)
  })
  default     = {}
  description = <<DESCRIPTION
Configuration object for the Build VM to be created for managing the implementation services.

- `name` - (Optional) The name of the Build VM. If not provided, a name will be generated.
- `sku` - (Optional) The VM size/SKU for the Build VM. Default is "Standard_B2s".
- `tags` - (Optional) Map of tags to assign to the Build VM.
- `enable_telemetry` - (Optional) Whether telemetry is enabled for the Build VM module. Default is true.
DESCRIPTION
}

variable "name_prefix" {
  #TODO: add a validation rule to keep this under 10 characters only alphanumeric lowercase
  type        = string
  default     = null
  description = <<DESCRIPTION
Optional prefix to be used for naming resources.

This prefix will be applied to all resource names generated by the module. It is useful for ensuring consistent naming conventions across deployments without requiring explicit names for each resource. The prefix should be kept under 10 characters and use only alphanumeric lowercase characters to avoid Azure naming limitations.
DESCRIPTION
}

variable "tags" {
  type        = map(string)
  default     = null
  description = <<DESCRIPTION
Map of tags to be assigned to all resources created by this module.

Tags are key-value pairs that help organize and manage Azure resources. These tags will be applied to all resources created by the module, enabling consistent resource governance, cost tracking, and operational management across the AI/ML landing zone infrastructure.
DESCRIPTION
}
